### PR TITLE
📝 Contributors are required to assign copyright to Zinc Collective LLC

### PR DESCRIPTION
**Pull request by zspencer**
In @drlau's patch; he made some really useful points that I wanted to integrate: https://github.com/zinc-collective/compensated/pull/41

However, I'm getting into some git-wigglyness because we had made some changes that made the `0.X` branch in our repository go a bit too far ahead of @drlau's fork.

I've submitted a  patch to his patch that brings it up to date for now; and have asked if he feels comfortable with us merging this directly (so long as it doesn't remove his authorship attribution)

### CODE REVIEW

**Comment by drllau** [comment]
There shouldn't be conflicts as I added several files and expanded around CONTRIBUTIONS ... you can try just replace that file holus bolus as it was basically a stub. I still need to update it as per Zees current plan on license including within each major version so I'll wait until people read and ack/nak the ideas to merge back into Master branch

**Review by drllau — CHANGES_REQUESTED** [review]
I'd like to see some clarity on what is meant by major vs minor version as Zee wants "free" gratis upgrades within major to licensees. So what is meant by minor?
1. new languages?
2. new frameworks?
3. different payment processors?
4. multiple crossborder currencies
5. useable outside US (Stripe operates in 30+ jurisdictions)

**Review by drllau — COMMENTED** [review]
So not clear what is needed here. You want to keep my plain English interpretation and link to subtopics in the green portions further down? This is just a matter of line shuffling.
On the other hand a lot of the MUST, SHOULD etc I feel is a little demeaning, we're all adults and shouldn't need to be treated as naughty schoolkids. The best way is a carrot approach using [OpenBadges](https://openbadges.org/)
In legalspeak, positivism (aspiring to what should be) rather than normative (trying to punish outside norm)

**Comment by zspencer** [comment]
Re: What's needed here - Only your assent to assign the copyright for your commit in this patch to Zinc Collective. To do so, please follow [the directions for assigning copyright in the contributing guide](https://github.com/zinc-collective/compensated/blob/0.X/CONTRIBUTING.md#assignment-of-ownership-to-zinc-collective).

Re: Conflicts - Unfortunately, there are significant conflicts between the `drlau/patch-2` branch and the `zinc-collective/0.X` branch. I believe this is because of a "rough edge" when someone creates a branch off of another branch that was merged in later, or when their master (aka `0.X`) branch is behind the `zinc-collective/0.X` branch. This is a patch that does my best to remediate the conflicts but is by no means the only way forward. If you would like to take a stab at resolving the conflicts or creating a new patch off of the `zinc-collective/0.X` branch I'm happy to merge that instead.

Re: Versioning - The goal is to follow [Semantic Versioning](https://semver.org/) where once we hit 1.0; any _breaking changes_ move us to 2.0. Any _non-breaking changes_ are added to 1.0. A goal I have before calling this "1.0" is having a high degree of confidence that we can make significant additions (new payment processors, new languages/frameworks, etc.) without breaking the existing functionality. I am defining "breaking changes" as requiring any user to change their code in order to adopt the new version.

Re: Positivism - Yes! I 100% agree here. The RFC style syntax was added because I have been getting feedback from folks who are a bit less willing to put themselves out there that having clear and explicit guidelines about what one must and must not do makes it safer and easier for them to approach the project. I think the open badges project is quite interesting and am happy to hear suggestions on how we could apply it in a 'yes, and' method that complements the standard RFC `must/should/may` syntax?

Re: Line shuffling - I'm not entirely sure what you mean here? I am trying to merge the suggestions you in the `drlau/patch-2` branch with the most up-to-date `CONTRIBUTING.md` in `zinc-collective/0.X`.

**Review by drllau — APPROVED** [review]

**Pull request merged**
