### PR TITLE
fixed a couple instances of mangled json

### PR DESCRIPTION
**Pull request by ghost**
Not sure what the cause of this was, but alas, an easy fix

### CODE REVIEW

**Comment by zspencer** [comment]
Ahhh, that is because the JSON files are _erb_ fixtures, not plain old json. They should be named `<filename>.json.erb` so that it's a bit more clear that they are intended for data to be interpolatable into them.

See: 
- https://github.com/zinc-collective/compensated/blob/0.X/compensated-ruby/spec/stripe/event_parser_spec.rb#L252
- https://github.com/zinc-collective/compensated/blob/0.X/compensated-ruby/spec/stripe/event_parser_spec.rb#L257
- https://github.com/zinc-collective/compensated/blob/0.X/compensated-ruby/spec/stripe/event_parser_spec.rb#L287
- https://github.com/zinc-collective/compensated/blob/0.X/compensated-ruby/spec/stripe/event_parser_spec.rb#L292


You can use the `compensated_event_body` method defined in the [Compensated::Spec::Helpers](https://github.com/zinc-collective/compensated/blob/ddc7e774a6bcbcdf9fad2beeb2a92e757fd0a687/compensated-spec/lib/compensated/spec.rb#L8) module to interpolate your own values into the JSON like so:

```
$ bundle console
> require 'json'
> include Compensated::Spec::Helpers
# => Object
> puts JSON.parse(compensated_event_body('stripe/charge.succeeded.api-v2014-11-05.json'))
```

You can see examples of this in the [feature definition for using fixutres](https://github.com/zinc-collective/compensated/blob/ddc7e774a6bcbcdf9fad2beeb2a92e757fd0a687/compensated-spec/features/using-fixtures.feature), and there is corresponding code illustrating it in the underying [step definitions](https://github.com/zinc-collective/compensated/blob/ddc7e774a6bcbcdf9fad2beeb2a92e757fd0a687/compensated-spec/features/steps.rb#L14)

**Review by zspencer — CHANGES_REQUESTED** [review]
These are seams so that we can interpolate ERB; I would be totally down to merge a PR that renamed them to `<file-name>.json.erb`; but merging them as is would break consumers of the `compensated-spec` gem

(Apologies for the double comment, Github is a but and didn't let me just post one and request changes)

**Comment by ghost** [comment]
Ahh I see. Shall I close this issue and make a PR to rename the files?

**Comment by zspencer** [comment]
@lanegrant that'd be awesome! Thank you!

**Pull request closed without merging**
